name: Build test
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
    - name: Smoke tests container image
      run: |
        pytest
      env:
        IB_ACCOUNT: ${{ secrets.IB_ACCOUNT }}
        IB_PASSWORD: ${{ secrets.IB_PASSWORD }}
