name: Deploy to docker hub

on:
   push:
     branches:    
      - master
      - develop
     tags:
       - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: build-push
        uses: docker/build-push-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            registry: registry.hub.docker.com
            repository: manhinhang/ib-gateway-docker
